import esbuild from "esbuild";
import process from "process";
import { builtinModules, createRequire } from "node:module";
import { promises as fs } from "fs";
import { join } from "path";

export const prod = process.argv[2] === "production";
export const watchMode = process.argv[2] === "watch";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

export const obsidianPluginExternal = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules,
];

export const dataUrlImageLoader = {
  ".png": "dataurl",
  ".svg": "dataurl",
};

export const broadDataUrlImageLoader = {
  ".png": "dataurl",
  ".jpg": "dataurl",
  ".gif": "dataurl",
  ".svg": "dataurl",
};

export const renameBundledCssPlugin = {
  name: "rename-bundled-css",
  setup(build) {
    build.onEnd(async () => {
      try {
        await fs.rename(join(process.cwd(), "main.css"), join(process.cwd(), "styles.css"));
      } catch (error) {
        if (error.code !== "ENOENT") console.error("Error renaming bundled CSS:", error);
      }
    });
  },
};

export function createPluginBuildOptions(options = {}) {
  return {
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: options.external ?? obsidianPluginExternal,
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    minify: prod,
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    ...options,
    plugins: [...(options.plugins ?? []), renameBundledCssPlugin],
  };
}

export async function runPluginBuild(options = {}) {
  const context = await esbuild.context(createPluginBuildOptions(options));
  if (watchMode) {
    await context.watch();
    return;
  }
  await context.rebuild();
  process.exit(0);
}

/**
 * maplibre-gl 6 loads its worker from a URL rather than an inline blob, which a
 * bundled, server-less Obsidian plugin can't provide. This pre-bundles the calling
 * package's nested maplibre-gl 6 worker (with its shared chunk) into one
 * self-contained ES module and exposes its source under the `maplibre-worker-bundle`
 * import; the provider serves it via a blob URL at runtime with installMaplibreWorker.
 * Only maplibre-gl 6 providers need this. Usage:
 *   runPluginBuild({ plugins: [await createMaplibreWorkerInlinePlugin()] })
 */
export async function createMaplibreWorkerInlinePlugin() {
  const workerBuild = await esbuild.build({
    // Resolved rather than spelled out: npm hoists maplibre-gl to the workspace
    // root when a plugin's version is the common one, and nests it when the
    // plugin pins a different major. A literal node_modules path finds only the
    // nested case. This file is vendored into each package, so resolution starts
    // from that package and picks up whichever copy it actually builds against.
    entryPoints: [createRequire(import.meta.url).resolve("maplibre-gl/dist/maplibre-gl-worker.mjs")],
    bundle: true,
    format: "esm",
    minify: true,
    legalComments: "none",
    write: false,
  });
  const workerCode = workerBuild.outputFiles[0].text;
  return {
    name: "maplibre-worker-inline",
    setup(build) {
      build.onResolve({ filter: /^maplibre-worker-bundle$/ }, () => ({
        path: "maplibre-worker-bundle",
        namespace: "maplibre-worker",
      }));
      build.onLoad({ filter: /.*/, namespace: "maplibre-worker" }, () => ({
        contents: workerCode,
        loader: "text",
      }));
    },
  };
}

export async function copyStylesIfPresent() {
  try {
    await fs.copyFile(join(process.cwd(), "src", "styles.css"), join(process.cwd(), "styles.css"));
    console.log("✓ CSS file copied");
  } catch (error) {
    if (error.code !== "ENOENT") console.error("Error copying CSS:", error);
  }
}
