import { App } from "obsidian";
import type * as GeoJSON from "geojson";
import { type UnitsSystem } from "places-shared/units";
import { type TrackColorBy } from "places-shared/track";
import { MapPlace } from "places-shared/overlay";
import { IPlaceExtensionSettings, type MapRenderRequest, type ResolvedMapConfig, type MetricWindow } from "places-shared/settings";
import { MapBlockProcessorBase, CommonMapSettings, type MapDataUpdateContext, type MapDataUpdateResult, type MapControlHandle, type MapCameraApplyResult, type MapIncrementalUpdateCapabilities } from "places-shared/services";
import { type MapCameraIntent } from "places-shared/render";
import type * as maplibregl from 'maplibre-gl';
export type MapContainer = HTMLElement;
type MapLibreStyle = string | maplibregl.StyleSpecification;
export declare abstract class MapLibreProviderBase extends MapBlockProcessorBase {
    private readonly units;
    protected app: App;
    protected extensionSettings: IPlaceExtensionSettings;
    private poiDiscoveryHandler;
    private overlayHandler;
    private static tileCacheProtocolRegistered;
    private static readonly auditedStyleDocuments;
    private static readonly deduplicatedStyleCounts;
    private initializedMaps;
    private viewportTrackCleanups;
    private viewportTrackControllers;
    private symbolImagePreparationCleanups;
    private wiredWaypointClickLayers;
    private waypointClickWiredMaps;
    private trackLineLayers;
    private trackLineClickWiredMaps;
    private trackInspectionPanels;
    private symbolVisibilityHidden;
    private trackUserVisibility;
    private symbolClusterData;
    readonly supportsLiveMarkerVisibility = true;
    private static nextRenderId;
    private getDocumentStyleAudit;
    private deduplicateDocumentStyles;
    private getMapRuntimeAudit;
    private getRuntimeIdentity;
    constructor(app: App, extensionSettings: IPlaceExtensionSettings, units: UnitsSystem, developerMode?: boolean);
    protected addMapLibreProtocol(customProtocol: string, loadFn: Parameters<typeof maplibregl.addProtocol>[1]): void;
    protected abstract getStyleUrl(style: string): MapLibreStyle | undefined;
    protected abstract getProviderClassName(): string;
    protected getProviderIntegration(): string;
    protected constructMap(options: maplibregl.MapOptions): maplibregl.Map;
    private getProviderStateId;
    private getMapInstance;
    private attachMapTool;
    private buildMapToolAttachment;
    private attachMapToolUnguarded;
    private syncMapTools;
    protected getSupportedStyles(): string[];
    protected prepareStyle(blockSettings: ResolvedMapConfig): Promise<MapLibreStyle | undefined>;
    protected supportsTileCache(): boolean;
    protected getTileCacheProviderName(): string;
    protected getCacheableResourceUrl(url: string): string;
    protected getCacheableResourceHeaders(): Record<string, string> | undefined;
    private prepareCacheableStyle;
    protected ensureTileCacheProtocol(): void;
    private fetchCacheableResource;
    private prepareTileCacheStyle;
    private inlineTileJson;
    protected toCacheProtocolUrl(url: string, baseUrl?: string): string;
    private applyInitialViewport;
    private encodeTemplateUrl;
    private resolveRemoteUrl;
    processPlaceCodeBlock(places: MapPlace[], mapContainerElement: HTMLElement, request: MapRenderRequest): Promise<void>;
    private processPlaceCodeBlockAsync;
    private runWhenStyleReady;
    private setupMapContainer;
    private showStyleError;
    private createMapInstance;
    private setupZoomVariable;
    private setupStatePersistence;
    private setupCameraGestureTracking;
    private setupDebugOverlay;
    private refreshDebugOverlayData;
    getMapControlHandle(container: HTMLElement): MapControlHandle | null;
    private highlightPlace;
    private clearPlaceHighlight;
    private focusSymbolMarker;
    private clearSymbolMarkerFocus;
    private openPopupForPlace;
    private createMapComponent;
    private setupEventHandlers;
    private applyPOIFilters;
    private debugData;
    private onMapLoad;
    private ensureGeoJsonSource;
    private profileNextRenderAndIdle;
    private updateGeoJsonSource;
    private setupTextLabelLayer;
    private initializeMapView;
    private addClusteredMarkers;
    private addSymbolClusteredMarkers;
    private addClusterSourceAndLayers;
    private addOverlayPointLayer;
    private handleOverlayPointClick;
    private addIconMarkers;
    private addSymbolLayerMarkers;
    private addSymbolMarkerLayer;
    private buildSymbolMarkerData;
    private ensureSymbolMarkerImages;
    private scheduleSymbolMarkerImages;
    private getSymbolIconImageId;
    private refreshSymbolLayerData;
    private ensureSymbolIconImage;
    private resolveBadgeOffsetPx;
    private createPointFeature;
    private createHtmlMarkerFeature;
    private createIconMarkerWithReturn;
    protected onMarkerClick(map: maplibregl.Map, feature: GeoJSON.Feature, settings: CommonMapSettings): void;
    protected onPlacesLayerClick(e: maplibregl.MapLayerMouseEvent, settings: CommonMapSettings): void;
    private toggleGeoJsonOverlay;
    private applyZoomRange;
    private addDynamicOverlayLayers;
    private addDynamicWaypointLayers;
    private registerTrackLineLayer;
    private wireTrackLineClick;
    private openOverlappingTracksPopup;
    private showTrackInspectionPanel;
    private wireWaypointClick;
    private addDynamicRouteLabelLayer;
    private getViewportTrackBucketKey;
    private resolveTrackGeoJson;
    private createViewportTrackFeatures;
    private updateViewportTrackBucket;
    private showGeoJsonOverlayAndFitBounds;
    private clearTrackLayers;
    protected createPopup(map: maplibregl.Map, place: MapPlace | undefined, coordinates: [number, number], settings: CommonMapSettings, options?: {
        toggleOverlay?: boolean;
        inspectTrack?: boolean;
    }): void;
    private enrichPlaceSection;
    private showInitialTracks;
    private showTrackForPlace;
    private getTrackRenderSignature;
    private handleClusteringModeChange;
    private removeMapLayersAndSources;
    private setLayersVisibility;
    private removeDynamicOverlayLayers;
    private removeTrackLayersById;
    private setupViewportTrackLoading;
    protected showTrackAndFitBounds(map: maplibregl.Map, place: MapPlace, coloringType?: TrackColorBy, gradeWindow?: MetricWindow): void;
    protected showMultipleTracks(map: maplibregl.Map, places: MapPlace[], settings: CommonMapSettings): void;
    private addFrequencyOverlayLayer;
    protected showTrack(map: maplibregl.Map, place: MapPlace): void;
    private extendBoundsWithOverlays;
    protected getMapOptions(_blockSettings: ResolvedMapConfig): Record<string, unknown>;
    private setupTileFailureReporting;
    private sanitizeMapError;
    private setupContextMenu;
    protected processOverlays(map: maplibregl.Map, _mapContainer: HTMLElement, request: MapRenderRequest, places: MapPlace[]): Promise<void>;
    getCurrentPlaces(container: HTMLElement): MapPlace[] | null;
    getIncrementalUpdateCapabilities(): Readonly<MapIncrementalUpdateCapabilities>;
    updateMapData(container: HTMLElement, newPlaces: MapPlace[], request: MapRenderRequest, context?: MapDataUpdateContext): Promise<MapDataUpdateResult>;
    private persistViewportForRebuild;
    private performMapDataUpdate;
    applyCamera(container: HTMLElement, camera: MapCameraIntent, request: MapRenderRequest): MapCameraApplyResult;
    applyMarkerVisibility(container: HTMLElement, hiddenPlaceIds: readonly string[]): void;
    private applyTrackFilterVisibility;
    private recordTrackUserVisibility;
    private setDynamicOverlayVisibility;
    private applyClusteredData;
    private syncVisibleTrackOverlays;
    private updateClusteredMarkersIncrementally;
    private updateTextLabelLayer;
    setGeocodingSearchMarkers(places: MapPlace[], container: HTMLElement): void;
    cleanup(): void;
}
export {};
