import type * as maplibregl from 'maplibre-gl';
import { MapPlace } from "places-shared/overlay";
import { ViewportClusteringManager, type MapCameraGuard } from "places-shared/map";
import { type MapRenderRequest, type ResolvedMapConfig } from "places-shared/settings";
import { CommonMapSettings } from "places-shared/services";
export interface TrackState {
    place: MapPlace;
    settings: CommonMapSettings;
    trackIndex: number;
    renderSignature: string;
    renderMode?: 'dynamic' | 'indexed' | 'viewport-batch';
}
export declare class MapState {
    private static instances;
    private visibleTracks;
    private trackCounter;
    private placeMarkers;
    private placeMarkerSignatures;
    private currentPlaces;
    private currentSettings;
    private currentBlockSettings;
    private currentRenderRequest;
    private clusteringManager;
    private defaultTrackState;
    private overlayLineLayerCount;
    private embeddedTrackOverlayIndices;
    private placeFilePathToOverlayIndex;
    private visibleGeoJsonOverlays;
    private cameraGuard;
    private constructor();
    static for(map: maplibregl.Map): MapState;
    static cleanup(map: maplibregl.Map): void;
    getCameraGuard(): MapCameraGuard;
    getVisibleTracks(): Map<string, TrackState>;
    hasTrack(placeId: string): boolean;
    getTrack(placeId: string): TrackState | undefined;
    setTrack(placeId: string, state: TrackState): void;
    removeTrack(placeId: string): boolean;
    getNextTrackIndex(): number;
    getPlaceMarkers(): Map<string, maplibregl.Marker>;
    setPlaceMarker(placeId: string, marker: maplibregl.Marker): void;
    getPlaceMarker(placeId: string): maplibregl.Marker | undefined;
    getPlaceMarkerRenderSignature(placeId: string): string | undefined;
    setPlaceMarkerSignature(placeId: string, signature: string): void;
    deletePlaceMarkerSignature(placeId: string): void;
    setPlaceMarkerWithSignature(placeId: string, marker: maplibregl.Marker, markerSignature: string): void;
    deletePlaceMarkerWithSignature(placeId: string): maplibregl.Marker | undefined;
    setCurrentPlaces(places: MapPlace[]): void;
    getCurrentPlaces(): MapPlace[];
    private placesById;
    getPlaceById(placeId: string): MapPlace | undefined;
    setCurrentSettings(settings: CommonMapSettings): void;
    getCurrentSettings(): CommonMapSettings | null;
    setCurrentBlockSettings(settings: ResolvedMapConfig): void;
    getCurrentBlockSettings(): ResolvedMapConfig | null;
    setCurrentRenderRequest(request: MapRenderRequest): void;
    getCurrentRenderRequest(): MapRenderRequest | null;
    setClusteringManager(manager: ViewportClusteringManager<maplibregl.Marker> | null): void;
    getClusteringManager(): ViewportClusteringManager<maplibregl.Marker> | null;
    setDefaultTrackState(state: 'visible' | 'hidden'): void;
    getDefaultTrackState(): 'visible' | 'hidden';
    setOverlayLineLayerCount(count: number): void;
    getOverlayLineLayerCount(): number;
    setEmbeddedTrackOverlayIndices(indices: number[]): void;
    getEmbeddedTrackOverlayIndices(): number[];
    setPlaceFilePathToOverlayIndex(filePath: string, overlayIndex: number): void;
    getOverlayIndexForPlace(filePath: string): number | undefined;
    isGeoJsonOverlayVisible(overlayIndex: number): boolean;
    setGeoJsonOverlayVisible(overlayIndex: number, visible: boolean): void;
}
export declare function isNonInteractivePlace(place: MapPlace | undefined): boolean;
export declare function hasDisplayableContent(place: MapPlace | undefined): boolean;
